# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CrosswordSolverKing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CrosswordSolverKing
  pod 'Google-Mobile-Ads-SDK'
  pod 'PersonalizedAdConsent'

  target 'CrosswordSolverKingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CrosswordSolverKingUITests' do
    # Pods for testing
  end

end
